export const LANGUAGES = [
  { name: 'English', native: 'English', code: 'en-US' },
  { name: 'Hindi', native: 'हिन्दी', code: 'hi-IN' },
  { name: 'Tamil', native: 'தமிழ்', code: 'ta-IN' },
  { name: 'Telugu', native: 'తెలుగు', code: 'te-IN' },
  { name: 'Kannada', native: 'ಕನ್ನಡ', code: 'kn-IN' },
  { name: 'Malayalam', native: 'മലയാളം', code: 'ml-IN' },
  { name: 'Bengali', native: 'বাংলা', code: 'bn-IN' },
  { name: 'Marathi', native: 'मराठी', code: 'mr-IN' },
  { name: 'Gujarati', native: 'ગુજરાતી', code: 'gu-IN' },
  { name: 'Punjabi', native: 'ਪੰਜਾਬੀ', code: 'pa-IN' },
  { name: 'Urdu', native: 'اردو', code: 'ur-PK' },
  { name: 'Nepali', native: 'नेपाली', code: 'ne-NP' },
  { name: 'Sinhala', native: 'සිංහල', code: 'si-LK' },
  { name: 'Khmer', native: 'ខ្មែរ', code: 'km-KH' },
  { name: 'Arabic', native: 'العربية', code: 'ar-SA' },
  { name: 'Spanish', native: 'Español', code: 'es-ES' },
  { name: 'French', native: 'Français', code: 'fr-FR' },
  { name: 'German', native: 'Deutsch', code: 'de-DE' },
  { name: 'Italian', native: 'Italiano', code: 'it-IT' },
  { name: 'Portuguese', native: 'Português', code: 'pt-BR' },
  { name: 'Dutch', native: 'Nederlands', code: 'nl-NL' },
  { name: 'Polish', native: 'Polski', code: 'pl-PL' },
  { name: 'Swedish', native: 'Svenska', code: 'sv-SE' },
  { name: 'Norwegian', native: 'Norsk', code: 'no-NO' },
  { name: 'Finnish', native: 'Suomi', code: 'fi-FI' },
  { name: 'Danish', native: 'Dansk', code: 'da-DK' },
  { name: 'Czech', native: 'Čeština', code: 'cs-CZ' },
  { name: 'Romanian', native: 'Română', code: 'ro-RO' },
  { name: 'Hungarian', native: 'Magyar', code: 'hu-HU' },
  { name: 'Russian', native: 'Русский', code: 'ru-RU' },
  { name: 'Japanese', native: '日本語', code: 'ja-JP' },
  { name: 'Chinese', native: '中文', code: 'zh-CN' },
  { name: 'Korean', native: '한국어', code: 'ko-KR' },
  { name: 'Turkish', native: 'Türkçe', code: 'tr-TR' },
  { name: 'Vietnamese', native: 'Tiếng Việt', code: 'vi-VN' },
  { name: 'Thai', native: 'ไทย', code: 'th-TH' },
  { name: 'Indonesian', native: 'Bahasa Indonesia', code: 'id-ID' },
  { name: 'Malay', native: 'Bahasa Melayu', code: 'ms-MY' },
  { name: 'Filipino', native: 'Filipino', code: 'fil-PH' },
  { name: 'Swahili', native: 'Kiswahili', code: 'sw-KE' },
  { name: 'Hausa', native: 'Hausa', code: 'ha-NG' },
  { name: 'Amharic', native: 'አማርኛ', code: 'am-ET' },
];
